// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDixCqNaQBtDWNsjjAgNFdqM7YJr0Mkbk0',
    appId: '1:643296651939:web:414a5381213835d5ed6d16',
    messagingSenderId: '643296651939',
    projectId: 'crud-d2f00',
    authDomain: 'crud-d2f00.firebaseapp.com',
    storageBucket: 'crud-d2f00.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSB_JKxjPSXAuOOA9WFAiUrJSw7Jvc-9Q',
    appId: '1:643296651939:android:7545df95cc2343b5ed6d16',
    messagingSenderId: '643296651939',
    projectId: 'crud-d2f00',
    storageBucket: 'crud-d2f00.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDA3-b0ST0XpPHYiToHjKxNUb3vHZjULKM',
    appId: '1:643296651939:ios:5816d057be2c2674ed6d16',
    messagingSenderId: '643296651939',
    projectId: 'crud-d2f00',
    storageBucket: 'crud-d2f00.appspot.com',
    iosBundleId: 'com.magtech.crud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDA3-b0ST0XpPHYiToHjKxNUb3vHZjULKM',
    appId: '1:643296651939:ios:fe03b1faa401606ded6d16',
    messagingSenderId: '643296651939',
    projectId: 'crud-d2f00',
    storageBucket: 'crud-d2f00.appspot.com',
    iosBundleId: 'com.magtech.crud.RunnerTests',
  );
}
